name: transport_management
description: Smart Transport Management System.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: 0.19.0

  cupertino_icons: ^1.0.2
  go_router: ^6.2.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  flutter_screenutil: ^5.7.0

  #Riverpod
  flutter_riverpod: ^2.3.2
  riverpod_annotation: ^2.3.4

  #DI
  get_it: ^7.2.0
  injectable: ^2.1.0
  flutter_svg: ^2.0.4

  #DB
  hive_flutter: ^1.1.0

  #Network
  http: ^0.13.5

  #Information
  logger: ^1.3.0

  #toast
  fluttertoast: ^8.2.1

  #image
  cached_network_image: ^3.2.3
  firebase_core: ^2.31.0
  flutter_keyboard_visibility: ^6.0.0
  intl_phone_field: ^3.2.0
  pinput: ^3.0.1
  easy_date_timeline: ^1.0.3
  syncfusion_flutter_datepicker: ^25.1.39
  permission_handler: ^11.3.1
  image_picker: ^1.0.8
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0
  auto_size_text: ^3.0.0
  animated_notch_bottom_bar: ^1.0.3
  dotted_border: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.4.0
  freezed: ^2.3.2
  injectable_generator: ^2.1.4
  json_serializable: ^6.6.1
  riverpod_generator: ^2.3.11

  artisan:
    git:
      url: https://github.com/Wolfiz-2-0/artisan


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/svgs/
    - assets/pngs/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Thin.ttf
          weight: 100
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-Regular.ttf
          weight: 400
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
        - asset: assets/font/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/font/Poppins-Black.ttf
          weight: 900


