////********** AUTOGENERATED FILE: DO NOT REMOVE ANY COMMENT IN THIS STYLE **********////
////********** START IMPORTS **********////
import 'package:avcons/features/withdrawal/domain/data/withdrawal_remote_datasource.dart';
import 'package:avcons/features/withdrawal/domain/usecases/create_withdrawal_request.dart';
import 'package:avcons/features/withdrawal/domain/usecases/get_withdrawal_requests.dart';
import 'package:avcons/helpers/network_call_helper/network_call_helper.dart';
import 'package:logger/logger.dart';
////********** END IMPORTS **********////

class WithdrawalRemoteDataSourceImp implements WithdrawalRemoteDataSource {
  final Logger _logger;
  final NetworkCallHelper _networkCallHelper;

  WithdrawalRemoteDataSourceImp({
    required Logger logger,
    required NetworkCallHelper networkCallHelper,
  })  : _logger = logger,
        _networkCallHelper = networkCallHelper;

  @override
  Future<CreateWithdrawalRequestUsecaseOutput> createWithdrawalRequest(
      CreateWithdrawalRequestUsecaseInput input) {
    throw UnimplementedError();
  }

  @override
  Future<GetWithdrawalRequestsUsecaseOutput> getWithdrawalRequests(
      GetWithdrawalRequestsUsecaseInput input) {
    throw UnimplementedError();
  }

////********** START METHODS **********////

////********** END METHODS **********////
}
