import 'package:injectable/injectable.dart';
import 'package:transport_management/features/withdrawal/domain/data/withdrawal_remote_datasource.dart';
import 'package:transport_management/features/withdrawal/domain/repository/withdrawal_repository.dart';
import 'package:transport_management/features/withdrawal/domain/usecases/create_withdrawal_request.dart';
import 'package:transport_management/features/withdrawal/domain/usecases/get_withdrawal_requests.dart';

////********** AUTOGENERATED FILE: DO NOT REMOVE ANY COMMENT IN THIS STYLE **********////
////********** START IMPORTS **********////

////********** END IMPORTS **********////

@LazySingleton(as: WithdrawalRepository)
class WithdrawalRepositoryImp implements WithdrawalRepository {
////********** START VARIABLES **********////
  final WithdrawalRemoteDataSource _withdrawalRemoteDataSource;
////********** END VARIABLES **********////

  WithdrawalRepositoryImp({
////********** START RECEIVE VALUES **********////
    required WithdrawalRemoteDataSource withdrawalRemoteDataSource,
////********** END RECEIVE VALUES **********////
  }) :
////********** START SET VALUES **********////
        _withdrawalRemoteDataSource = withdrawalRemoteDataSource
////********** END SET VALUES **********////
  ;

////********** START METHODS **********////
  /// [CreateWithdrawalRequestUsecaseInput] is received to [createWithdrawalRequest] method as parameter
  /// [CreateWithdrawalRequestUsecaseOutput] is returned from [createWithdrawalRequest] method
  @override
  Future<CreateWithdrawalRequestUsecaseOutput> createWithdrawalRequest(
      CreateWithdrawalRequestUsecaseInput input) async {
    return _withdrawalRemoteDataSource.createWithdrawalRequest(input);
  }

  /// [GetWithdrawalRequestsUsecaseInput] is received to [getWithdrawalRequests] method as parameter
  /// [GetWithdrawalRequestsUsecaseOutput] is returned from [getWithdrawalRequests] method
  @override
  Future<GetWithdrawalRequestsUsecaseOutput> getWithdrawalRequests(
      GetWithdrawalRequestsUsecaseInput input) async {
    return _withdrawalRemoteDataSource.getWithdrawalRequests(input);
  }

////********** END METHODS **********////
}
