////********** AUTOGENERATED FILE: DO NOT REMOVE ANY COMMENT IN THIS STYLE **********////
////********** START IMPORTS **********////
import 'package:transport_management/features/auth/domain/usecases/current_user.dart';
import 'package:transport_management/features/auth/domain/usecases/delete_auth.dart';
import 'package:transport_management/features/auth/domain/usecases/delete_user.dart';
import 'package:transport_management/features/auth/domain/usecases/get_auth.dart';
import 'package:transport_management/features/auth/domain/usecases/get_vehicle_models.dart';
import 'package:transport_management/features/auth/domain/usecases/initiate_reset_password_verification.dart';
import 'package:transport_management/features/auth/domain/usecases/initiate_verification.dart';
import 'package:transport_management/features/auth/domain/usecases/login_driver.dart';
import 'package:transport_management/features/auth/domain/usecases/register_driver.dart';
import 'package:transport_management/features/auth/domain/usecases/reset_password.dart';
import 'package:transport_management/features/auth/domain/usecases/save_auth.dart';
import 'package:transport_management/features/auth/domain/usecases/update_profile.dart';
import 'package:transport_management/features/auth/domain/usecases/verify_otp.dart';
import 'package:transport_management/infrastructure/repository.dart';
////********** END IMPORTS **********////

abstract class AuthRepository extends Repository {
////********** START METHODS **********////
  /// [LoginUsecaseInput] is received to [login] method as parameter
  /// [LoginUsecaseOutput] is returned from [login] method
  Future<LoginDriverUsecaseOutput> login(LoginDriverUsecaseInput input);

  /// [RegisterUsecaseInput] is received to [register] method as parameter
  /// [RegisterUsecaseOutput] is returned from [register] method
  Future<RegisterDriverUsecaseOutput> register(
      RegisterDriverUsecaseInput input);

  /// [SaveAuthUsecaseInput] is received to [saveAuth] method as parameter
  /// [SaveAuthUsecaseOutput] is returned from [saveAuth] method
  Future<SaveAuthUsecaseOutput> saveAuth(SaveAuthUsecaseInput input);

  /// [GetAuthUsecaseInput] is received to [getAuth] method as parameter
  /// [GetAuthUsecaseOutput] is returned from [getAuth] method
  Future<GetAuthUsecaseOutput> getAuth(GetAuthUsecaseInput input);

  /// [DeleteAuthUsecaseInput] is received to [deleteAuth] method as parameter
  /// [DeleteAuthUsecaseOutput] is returned from [deleteAuth] method
  Future<DeleteAuthUsecaseOutput> deleteAuth(DeleteAuthUsecaseInput input);

  /// [CurrentUserUsecaseInput] is received to [currentUser] method as parameter
  /// [CurrentUserUsecaseOutput] is returned from [currentUser] method
  Future<CurrentUserUsecaseOutput> currentUser(CurrentUserUsecaseInput input);

  /// [DeleteUserUsecaseInput] is received to [deleteUser] method as parameter
  /// [DeleteUserUsecaseOutput] is returned from [deleteUser] method
  Future<DeleteUserUsecaseOutput> deleteUser(DeleteUserUsecaseInput input);

  /// [ResetPasswordUsecaseInput] is received to [resetPassword] method as parameter
  /// [ResetPasswordUsecaseOutput] is returned from [resetPassword] method
  Future<ResetPasswordUsecaseOutput> resetPassword(
      ResetPasswordUsecaseInput input);

  /// [UpdateProfileUsecaseInput] is received to [updateProfile] method as parameter
  /// [UpdateProfileUsecaseOutput] is returned from [updateProfile] method
  Future<UpdateProfileUsecaseOutput> updateProfile(
      UpdateProfileUsecaseInput input);

  /// [VerifyOtpUsecaseInput] is received to [verifyOtp] method as parameter
  /// [VerifyOtpUsecaseOutput] is returned from [verifyOtp] method
  Future<VerifyOtpUsecaseOutput> verifyOtp(VerifyOtpUsecaseInput input);

  /// [InitiateVerificationUsecaseInput] is received to [initiateVerification] method as parameter
  /// [InitiateVerificationUsecaseOutput] is returned from [initiateVerification] method
  Future<InitiateVerificationUsecaseOutput> initiateVerification(
      InitiateVerificationUsecaseInput input);

  /// [GetVehicleModelsUsecaseInput] is received to [getVehicleModels] method as parameter
  /// [GetVehicleModelsUsecaseOutput] is returned from [getVehicleModels] method
  Future<GetVehicleModelsUsecaseOutput> getVehicleModels(
      GetVehicleModelsUsecaseInput input);

  /// [InitiateResetPasswordVerificationUsecaseInput] is received to [resetPasswordInitiateVerification] method as parameter
  /// [InitiateResetPasswordVerificationUsecaseOutput] is returned from [resetPasswordInitiateVerification] method
  Future<InitiateResetPasswordVerificationUsecaseOutput>
      resetPasswordInitiateVerification(
          InitiateResetPasswordVerificationUsecaseInput input);

////********** END METHODS **********////
}
